server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/member/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowed-origin-patterns: '*'
            allowed-methods: '*'
            allow-credentials: true
            max-age: 3600

